export const CITIES_FETCH_STARTED = 'CITIES_FETCH_STARTED';
export const CITIES_FETCH_COMPLETED = 'CITIES_FETCH_COMPLETED';
export const CITIES_FETCH_FAILED = 'CITIES_FETCH_FAILED';
export const CITY_SELECTED = 'CITY_SELECTED';
export const CITY_DESELECTED = 'CITY_DESELECTED';