export const COMMENTS_FETCH_STARTED = 'COMMENTS_FETCH_STARTED';
export const COMMENTS_FETCH_COMPLETED = 'COMMENTS_FETCH_COMPLETED';
export const COMMENTS_FETCH_FAILED = 'COMMENTS_FETCH_FAILED';

export const COMMENT_ADD_STARTED = 'COMMENT_ADD_STARTED'
export const COMMENT_ADD_COMPLETED = 'COMMENT_ADD_COMPLETED'
export const COMMENT_ADD_FAILED = 'COMMENT_ADD_FAILED'