export const COUNTRIES_FETCH_STARTED = 'COUNTRIES_FETCH_STARTED';
export const COUNTRIES_FETCH_COMPLETED = 'COUNTRIES_FETCH_COMPLETED';
export const COUNTRIES_FETCH_FAILED = 'COUNTRIES_FETCH_FAILED';
export const COUNTRY_SELECTED = 'COUNTRY_SELECTED';