
export const EVENT_FETCH_STARTED = 'EVENT_FETCH_STARTED';
export const EVENT_FETCH_COMPLETED = 'EVENT_FETCH_COMPLETED';
export const EVENT_FETCH_FAILED = 'EVENT_FETCH_FAILED';

export const EVENT_ADD_STARTED = 'EVENT_ADD_STARTED';
export const EVENT_ADD_COMPLETED = 'EVENT_ADD_COMPLETED';
export const EVENT_ADD_FAILED = 'EVENT_ADD_FAILED';

export const EVENT_DELETE_STARTED = 'EVENT_DELETE_STARTED';
export const EVENT_DELETE_COMPLETED = 'EVENT_DELETE_COMPLETED';
export const EVENT_DELETE_FAILED = 'EVENT_DELETE_FAILED';
