export const PLACE_FETCH_STARTED = 'PLACE_FETCH_STARTED'
export const PLACE_FETCH_COMPLETED = 'PLACE_FETCH_COMPLETED'
export const PLACE_FETCH_FAILED = 'PLACE_FETCH_FAILED'

export const PLACE_ADD_STARTED = 'PLACE_ADD_STARTED'
export const PLACE_ADD_COMPLETED = 'PLACE_ADD_COMPLETED'
export const PLACE_ADD_FAILED = 'PLACE_ADD_FAILED'