
export const PLAN_FETCH_STARTED = 'PLAN_FETCH_STARTED';
export const PLAN_FETCH_COMPLETED = 'PLAN_FETCH_COMPLETED';
export const PLAN_FETCH_FAILED = 'PLAN_FETCH_FAILED';

export const PLAN_ADD_STARTED = 'PLAN_ADD_STARTED';
export const PLAN_ADD_COMPLETED = 'PLAN_ADD_COMPLETED';
export const PLAN_ADD_FAILED = 'PLAN_ADD_FAILED';

export const PLAN_DELETE_STARTED = 'PLAN_DELETE_STARTED';
export const PLAN_DELETE_COMPLETED = 'PLAN_DELETE_COMPLETED';
export const PLAN_DELETE_FAILED = 'PLAN_DELETE_FAILED';
