export const TRIP_FETCH_STARTED = 'TRIP_FETCH_STARTED'
export const TRIP_FETCH_COMPLETED = 'TRIP_FETCH_COMPLETED'
export const TRIP_FETCH_FAILED = 'TRIP_FETCH_FAILED'

export const TRIP_ADD_STARTED = 'TRIP_ADD_STARTED'
export const TRIP_ADD_COMPLETED = 'TRIP_ADD_COMPLETED'
export const TRIP_ADD_FAILED = 'TRIP_ADD_FAILED'

export const TRIP_DELETE_STARTED = 'TRIP_DELETE_STARTED'
export const TRIP_DELETE_COMPLETED = 'TRIP_DELETE_COMPLETED'
export const TRIP_DELETE_FAILED = 'TRIP_DELETE_FAILED'


